site_name: Harry's Blog 


theme:  
  name: null
  custom_dir: mkdocs-windmill/mkdocs_windmill/
  #custom_dir: overrides



extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@Harry_Blockchain


# plugins: 
#  - search
#  - blog:
#     blog_dir: .